/* Static imports keep every provider in the Vercel function bundle. */
module.exports = {
  "besthdgayporn": require("./providers-src/besthdgayporn.js"),
  "blvietsub": require("./providers-src/blvietsub.js"),
  "boyfriendtv": require("./providers-src/boyfriendtv.js"),
  "fullboys": require("./providers-src/fullboys.js"),
  "fxggxt": require("./providers-src/fxggxt.js"),
  "fxggxtorg": require("./providers-src/fxggxtorg.js"),
  "gaycock4u": require("./providers-src/gaycock4u.js"),
  "gaykinkyporn": require("./providers-src/gaykinkyporn.js"),
  "gaypornhot": require("./providers-src/gaypornhot.js"),
  "gaypornvidsxxx": require("./providers-src/gaypornvidsxxx.js"),
  "gaystream": require("./providers-src/gaystream.js"),
  "gayxx": require("./providers-src/gayxx.js"),
  "geporner": require("./providers-src/geporner.js"),
  "gpornone": require("./providers-src/gpornone.js"),
  "gvhot": require("./providers-src/gvhot.js"),
  "gxtapes": require("./providers-src/gxtapes.js"),
  "igay69": require("./providers-src/igay69.js"),
  "justthegays": require("./providers-src/justthegays.js"),
  "krx18": require("./providers-src/krx18.js"),
  "menxtube": require("./providers-src/menxtube.js"),
  "nurgay": require("./providers-src/nurgay.js"),
  "tophdgayporn": require("./providers-src/tophdgayporn.js"),
  "traingon": require("./providers-src/traingon.js"),
  "videosxgays": require("./providers-src/videosxgays.js"),
  "xhamster": require("./providers-src/xhamster.js"),
  "xvideosgay": require("./providers-src/xvideosgay.js"),
};
