/* Static imports keep every provider in the Vercel function bundle. */
module.exports = {
  "besthdgayporn": require("../providers/besthdgayporn.js"),
  "blvietsub": require("../providers/blvietsub.js"),
  "boyfriendtv": require("../providers/boyfriendtv.js"),
  "fullboys": require("../providers/fullboys.js"),
  "fxggxt": require("../providers/fxggxt.js"),
  "fxggxtorg": require("../providers/fxggxtorg.js"),
  "gaycock4u": require("../providers/gaycock4u.js"),
  "gaykinkyporn": require("../providers/gaykinkyporn.js"),
  "gaypornhot": require("../providers/gaypornhot.js"),
  "gaypornvidsxxx": require("../providers/gaypornvidsxxx.js"),
  "gaystream": require("../providers/gaystream.js"),
  "gayxx": require("../providers/gayxx.js"),
  "geporner": require("../providers/geporner.js"),
  "gpornone": require("../providers/gpornone.js"),
  "gvhot": require("../providers/gvhot.js"),
  "gxtapes": require("../providers/gxtapes.js"),
  "igay69": require("../providers/igay69.js"),
  "justthegays": require("../providers/justthegays.js"),
  "krx18": require("../providers/krx18.js"),
  "menxtube": require("../providers/menxtube.js"),
  "nurgay": require("../providers/nurgay.js"),
  "tophdgayporn": require("../providers/tophdgayporn.js"),
  "traingon": require("../providers/traingon.js"),
  "videosxgays": require("../providers/videosxgays.js"),
  "xhamster": require("../providers/xhamster.js"),
  "xvideosgay": require("../providers/xvideosgay.js"),
};
